spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    include:
      - jwt
      - eureka
      - actuator
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
